### PR TITLE
Target .NET Standard 1.0 platform

### PR DESCRIPTION
**Pull request by jorgebay**
In the latest release `1.0.11`, by targeting .NET Standard 1.6 platform, we lost the other platforms (PCL, .NET Framework 4.5 and 4.6).

See:
- https://docs.microsoft.com/en-us/dotnet/articles/standard/library
- https://docs.microsoft.com/en-us/nuget/schema/target-frameworks

Here is a fix to target .NET Standard 1.0 platform to support all PCL profiles and .NET Framework 3.5+.

### CODE REVIEW

**Comment by jorgebay** [comment]
Related to #9

**Comment by MiloszKrajewski** [comment]
Thanks for that. I'll merge it and re-release it soon.

**Comment by jorgebay** [comment]
I've added `"net35"` but if u would like to drop support for it, `"netstandard1.0" would be enough for most users (PCL, .NET Framework 4.5, ...)

**Comment by MiloszKrajewski** [comment]
I guess that net35 does not have to be supported by netcore library, as long as it is supported by the "net2" release of lz4net. It seems like it is used by people doing Unity3D.

**Comment by jorgebay** [comment]
> I guess that net35 does not have to be supported by netcore library, as long as it is supported by the "net2" release of lz4net.

But how do you plan to maintain support for net2.0 on nuget? Do you mean you plan to publish a separate package for it on nuget?

Let me know if you want me to remove the `net35` target.

**Comment by jorgebay** [comment]
As an idea, you could have different `buildOptions/compile/includeFiles` for target `net20` and `netstandard1.0`.

**Comment by MiloszKrajewski** [comment]
O... K....
Now I'm puzzled. As .nupkg has subfolders:
* lib\net2
* lib\net4-client
* lib\portable-net4+win8+wpa81+MonoAndroid+MonoTouch+Xamarin.iOS
* lib\portable-net4+win8+wpa81+sl5+wp8+MonoAndroid+MonoTouch+Xamarin.iOS
* lib\netstandard1.6

I assumed that .NET4 application will actually reference the dll in "lib\net4-client" folder.
If not, I think it does not make sense to release this as the same package (I may end up with two packages: lz4net and lz4net.netcore).

The "net4-client" is acually two fastest one as it also contains C++ mixed mode assembly. If new release forces people to use "netstandard1.6" branch, they may not like it.

**Comment by jorgebay** [comment]
As [nuget.org was showing only the framework ".NET Standard 1.6"][1], I thought you were using the new tool chain (`dotnet package`) to generate the .nupkg, but looking deeper it seems like you are using a `fsx` to fill in the outputs of the nuget package.

To fix this:
- I'll change the `fsx` to output use the `netstandard1.0` moniker.
- I'll remove `net35` from the .NET Core project.

[1]: https://www.nuget.org/packages/lz4net/

**Comment by jorgebay** [comment]
Done!

**Comment by MiloszKrajewski** [comment]
I think now (1.0.14.93) it works fine (with "unsafe" implementation). Let me know if it isn't.

**Pull request merged**
